server:
  port: 8080

spring:
  application:
    name: analytics
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_analytics?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password # Change this based on local setup
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none # DB already strictly defined
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

jwt:
  secret: 9A45B670A98F7A8D7C8BE0D6F34C68B4A5D9C2E4F69B8A2C4D5E6F7A8B9C0D3E
  expiration: 86400000 # 1 day in milliseconds
